In [14]:
%matplotlib inline
import numpy as np # Library for multi-dimensional arrays and math operations on them 
import pandas as pd # Library for data manipulation and analysis
import os # Interfacing python with the operating system
import matplotlib.pyplot as plt #Plotting library
import seaborn as sns #Plotting library with some statistical tools 
import nltk # Natural Language Processing toolkit, similar as textblob below, both have useful functions
from textblob import TextBlob
import string
import time
import re # Basically a string processing and manipulation library
from datetime import datetime ## Manipulating datetime inputs
from matplotlib.ticker import FuncFormatter
import glob
import matplotlib.pylab as pl
from ovito.io import import_file, export_file
### My plotting style is inputted here #####
import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 150
plt.rcParams["font.family"] = "Ubuntu"
plt.style.use('C:/Users/Toumba/Documents/plotstyle.mplstyle')
plt.rcParams['axes.linewidth'] = 4
plt.rcParams['xtick.major.size'] = 8 
plt.rcParams['ytick.major.size'] = 8 
plt.rcParams['xtick.labelsize']=20
plt.rcParams['ytick.labelsize']=20
plt.rcParams['xtick.minor.visible']=True
plt.rcParams['ytick.minor.visible']=True
plt.rcParams['xtick.minor.size'] = 5 
plt.rcParams['ytick.minor.size'] = 5
plt.rcParams['xtick.minor.width'] = 1.5
plt.rcParams['ytick.minor.width'] = 1.5
plt.rcParams['xtick.major.width'] = 2
plt.rcParams['ytick.major.width'] = 2
plt.rcParams['xtick.major.pad']='8'
plt.rcParams['ytick.major.pad']='8'
#############################################
os.chdir('D:/University/Simulations/Dendronized_polymer/Analysis/HOOMD_DATA/G3_N1000/RUN_0')
if os.path.isdir('Lammps_Traj')==False:
    os.mkdir('Lammps_Traj')

#### Define Functions ####

######### Calculate Gyration Tensor #######################3
@njit(fastmath=True)
def rg_tens (r):
    
    N = r.shape[0]
    r2=np.zeros((3,3))
    for i in range (N):
        for j in range (N):
            r2[0,0]+=(r[i,0]-r[j,0])*(r[i,0]-r[j,0])#diag
            r2[1,0]+=(r[i,1]-r[j,0])*(r[i,1]-r[j,0])#ndiag
            r2[2,0]+=(r[i,2]-r[j,0])*(r[i,2]-r[j,0])#ndiag
            r2[0,1]+=(r[i,0]-r[j,1])*(r[i,0]-r[j,1])#ndiag
            r2[0,2]+=(r[i,0]-r[j,2])*(r[i,0]-r[j,2])#ndiag
            r2[1,1]+=(r[i,1]-r[j,1])*(r[i,1]-r[j,1])#diag
            r2[2,1]+=(r[i,2]-r[j,1])*(r[i,2]-r[j,1])#ndiag
            r2[1,2]+=(r[i,1]-r[j,2])*(r[i,1]-r[j,2])#ndiag
            r2[2,2]+=(r[i,2]-r[j,2])*(r[i,2]-r[j,2])# diag
    r2=r2/(2*N**2)
    #rg2=r2[0,0]**2+r2[1,1]**2+r2[2,2]**2
    return r2


In [18]:
filename='./traj_1.gsd'
to_store='Lammps_Traj/'+filename[2:]
if os.path.isdir(to_store)==False:
    os.mkdir(to_store)
pipeline=import_file(filename)
#pipe_exp=
# Loop over all frames of the sequence.
for frame_index in range(pipeline.source.num_frames):    

    # Calling FileSource.compute() loads the requested frame
    # from the sequence into memory and returns the data as a new
    # DataCollection:
    data = pipeline.source.compute(frame_index)

    # The source path and the index of the current frame
    # are attached as attributes to the data collection:
    print('Frame source:', data.attributes['SourceFile'])
    print('Frame index:', data.attributes['SourceFrame'])
    # Accessing the loaded frame data, e.g the particle positions:
    #print(data.particles.positions[...])

Frame source: D:/University/Simulations/Dendronized_polymer/Analysis/HOOMD_DATA/G3_N1000/RUN_0/traj_1.gsd
Frame index: 0
[[-66.56091309 -21.09638977  -0.72342265]
 [-66.01146698 -20.89933014  -1.44362676]
 [-65.35663605 -20.80408669  -2.14158559]
 ...
 [-56.43381882 -73.92931366 184.53451538]
 [-57.02912903 -72.08916473 185.33129883]
 [-57.82567215 -73.04118347 184.8326416 ]]
Frame source: D:/University/Simulations/Dendronized_polymer/Analysis/HOOMD_DATA/G3_N1000/RUN_0/traj_1.gsd
Frame index: 1
[[-66.56091309 -21.09638977  -0.72342265]
 [-66.01146698 -20.89933014  -1.44362676]
 [-65.35663605 -20.80408669  -2.14158559]
 ...
 [-56.43381882 -73.92931366 184.53451538]
 [-57.02912903 -72.08916473 185.33129883]
 [-57.82567215 -73.04118347 184.8326416 ]]
Frame source: D:/University/Simulations/Dendronized_polymer/Analysis/HOOMD_DATA/G3_N1000/RUN_0/traj_1.gsd
Frame index: 2
[[-63.2828598  -17.15643692 -12.95890999]
 [-64.13841248 -16.69250488 -13.10563946]
 [-65.00955963 -16.19341087 -13.29530

In [22]:


filename='./traj_1.gsd'
for frame_index in range(pipeline.source.num_frames):    
    data = pipeline.source.compute(frame_index)
    pos=data.particles.positions[:]

352

In [23]:
pos=data.particles.positions

39.977264404296875